#undef MAKE_CONSTRUCTOR_EXTENDS_CPP0X1
#undef MAKE_CONSTRUCTOR_EXTENDS_CPP0X2
#undef MAKE_CONSTRUCTOR_EXTENDS_CPP0X3
#undef MAKE_CONSTRUCTOR_EXTENDS_CPP0X4
#undef MAKE_CONSTRUCTOR_EXTENDS_CPP0X5
#undef MAKE_CONSTRUCTOR_EXTENDS_CPP0X6
#undef MAKE_CONSTRUCTOR_EXTENDS_CPP0X7
#undef MAKE_CONSTRUCTOR_EXTENDS_CPP0X8
#undef MAKE_CONSTRUCTOR_EXTENDS_CPP0X


#undef MAKE_CONSTRUCTOR1
#undef MAKE_CONSTRUCTOR2
#undef MAKE_CONSTRUCTOR3
#undef MAKE_CONSTRUCTOR4
#undef MAKE_CONSTRUCTOR5
#undef MAKE_CONSTRUCTOR6
#undef MAKE_CONSTRUCTOR7
#undef MAKE_CONSTRUCTOR8
#undef MAKE_CONSTRUCTOR

#undef ASSIGN_IMPL1
#undef ASSIGN_IMPL2
#undef ASSIGN_IMPL3
#undef ASSIGN_IMPL4
#undef ASSIGN_IMPL5
#undef ASSIGN_IMPL6
#undef ASSIGN_IMPL7
#undef ASSIGN_IMPL8
#undef MAKE_ASSIGN
